__title__ = 'hrflow'
__description__ = 'Python hrflow.ai API package'
__url__ = 'https://github.com/hrflow/python-hrflow-api'
__version__ = '1.9.0'
__author__ = 'HrFlow.ai'
__author_email__ = 'contact@hrflow.ai'
__license__ = 'MIT'